# Generated by Django 3.0.8 on 2020-07-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200715_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type',
            new_name='types',
        ),
    ]
